### ISSUE TITLE
patrick sprite

### ISSUE THREAD

**Issue by jawa-08** [balt-dev/robot-is-chill#66] opened 2022-05-27 01:09 UTC
i dont know if this is intended, but the patrick sprite for up sleep is blinking instead of sleeping

**Comment by RaidoCat** [comment] 2022-05-27 05:53
He just has insomnia when he looks up

**Comment by balt-is-you-and-shift** [comment] 2022-06-01 23:44
hhhh sorry

**Comment by krovellium** [comment] 2022-11-03 00:36
who is Patrick

**Comment by prismacrafter** [comment] 2022-11-03 01:40
from the hit game patrick's parabox

**Comment by krovellium** [comment] 2022-11-10 00:25
Real

**Comment by CenTdemeern1** [comment] 2022-11-23 23:15
@balt-dev bump

**Comment by krovellium** [comment] 2022-11-24 21:48
Why you gotta do me like that 
Also isn’t this issue fixed, just close it

**Comment by CenTdemeern1** [comment] 2022-11-25 00:17
> Why you gotta do me like that

If you mean marking your comments as off topic, I marked them correctly.

> Also isn’t this issue fixed, just close it

No, the issue is not fixed

**Comment by krovellium** [comment] 2022-11-25 02:09
Isn't it just a simple sprite reference issue (i'm assuming the sprite already exists just hasn't been correctly assigned)?

if so, its been almost 6 months to fix a single line of code
also "who is patrick" isn't off topic

**Comment by balt-dev** [comment] 2022-11-25 20:42
I forgot about this for like 6 months oops

**Comment by balt-dev** [comment] 2022-11-25 20:46
fixed in https://github.com/balt-dev/robot-is-chill/commit/42df6e5668d0304d0f97717fe530158f78e8033e

**Closed by balt-dev** 2022-11-25 20:46 UTC

**Comment by krovellium** [comment] 2022-11-25 20:54
> fixed in [42df6e5](https://github.com/balt-dev/robot-is-chill/commit/42df6e5668d0304d0f97717fe530158f78e8033e)
Thank you Balt

**Comment by CenTdemeern1** [comment] 2022-11-26 16:37
> also "who is patrick" isn't off topic 

By GitHub standards it is. You don't get to decide that.
